version: "3.9"

services:
  db:
    image: postgres:16
    container_name: chat_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat_api
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat_migrations
    command: alembic upgrade head
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    depends_on:
      - db

volumes:
  pg_data:
